In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/raw/tmdb_movies.csv")

In [5]:
df.shape

(10000, 7)

In [6]:
df_clean = df.drop_duplicates(subset="id", keep="first").copy()

In [7]:
df_clean.shape

(9695, 7)

In [8]:
df_clean["id"].duplicated().sum()

np.int64(0)

In [9]:
df_clean[["overview", "genres"]].isnull().sum()

overview    325
genres      506
dtype: int64

In [10]:
df_clean[["overview", "genres"]].isnull().any(axis=1).sum()

np.int64(710)

In [11]:
df_clean = df_clean.dropna(subset=["overview", "genres"]).copy()

In [12]:
df_clean[["overview", "genres"]].isnull().sum()

overview    0
genres      0
dtype: int64

In [13]:
df_clean.shape

(8985, 7)

In [14]:
df_clean.isnull().sum()

id               0
title            0
overview         0
genres           0
release_date    24
vote_average     0
popularity       0
dtype: int64

In [15]:
df_clean["genres"] = df_clean["genres"].apply(
    lambda x: "|".join(sorted(x.split("|")))
)

In [16]:
df_clean["genres"].nunique()

876

In [17]:
df_clean["genres"].value_counts().head(20)

genres
Drama                                730
Comedy                               379
Drama|Romance                        342
Comedy|Drama                         212
Action|Crime|Thriller                197
Comedy|Romance                       180
Crime|Drama|Thriller                 180
Horror|Thriller                      175
Horror                               170
Documentary                          169
Comedy|Drama|Romance                 160
Action|Adventure|Science Fiction     153
Crime|Drama                          143
Drama|Thriller                       129
Action|Thriller                      125
Drama|History                        122
Action|Crime|Drama                   117
Action|Crime|Drama|Thriller           86
Action|Crime                          81
Adventure|Animation|Comedy|Family     81
Name: count, dtype: int64

In [18]:
df_clean["overview"].str.strip().eq("").sum()

np.int64(0)

In [19]:
df_clean["title"].duplicated().sum()

np.int64(268)

In [20]:
df_clean[df_clean["title"].duplicated(keep=False)].sort_values("title").head(20)

,id,title,overview,genres,release_date,vote_average,popularity
6364,12219,12 Angry Men,During the trial of a man accused of his fathe...,Drama|TV Movie,1997-08-17,7.700,6.4381
249,389,12 Angry Men,The defense and the prosecution have rested an...,Drama,1957-04-10,8.571,31.6481
2480,23437,A Nightmare on Elm Street,"Teenagers Nancy, Quentin, Kris, Jesse and Dean...",Horror|Mystery|Thriller,2010-04-30,5.521,9.0103
636,377,A Nightmare on Elm Street,Teenagers in a small town are dropping like fl...,Horror,1984-11-09,7.351,18.9129
9321,1081012,Aftermath,"A returning war veteran, stricken with PTSD, g...",Action|Thriller,2024-09-27,6.200,5.0521
8111,390051,Aftermath,A fatal plane crash changes the lives of Roman...,Drama|Thriller,2017-02-28,5.700,5.6497
461,812,Aladdin,"In the boorish city of Agrabah, kind-hearted s...",Adventure|Animation|Family|Fantasy|Romance,1992-11-25,7.657,19.3729
1033,420817,Aladdin,A kindhearted street urchin named Aladdin emba...,Adventure|Family|Fantasy|Romance,2019-05-22,7.078,17.7295
580,12155,Alice in Wonderland,"Alice, now 19 years old, returns to the whimsi...",Adventure|Family|Fantasy,2010-03-03,6.644,20.4619
1283,12092,Alice in Wonderland,"On a golden afternoon, wildly curious young Al...",Adventure|Animation|Family|Fantasy,1951-08-09,7.190,14.2657
1336,49046,All Quiet on the Western Front,"Paul Baumer and his friends Albert and Muller,...",Drama|War,2022-10-07,7.743,14.0012
2258,143,All Quiet on the Western Front,When a group of idealistic young men join the ...,Drama|War,1930-04-29,7.758,9.0807
2912,399360,Alpha,"In the prehistoric past, Keda, a young and ine...",Adventure|Drama,2018-08-17,6.572,8.5722
7656,1284460,Alpha,"Alpha, a troubled 13-year-old lives with her s...",Drama|Horror|Science Fiction,2025-08-20,6.199,5.8716
6856,522459,Alter Ego,"Bent on bringing sexual predators to justice, ...",Drama,2017-07-07,0.000,6.4318
7098,1266791,Alter Ego,"Alex, a quiet forty-something, leads an ordina...",Comedy,2026-03-04,6.345,6.8376
1465,515333,Amateur,14-year-old basketball phenom Terron Forte has...,Drama,2018-04-06,6.403,13.7885
3132,30157,Amateur,"A man wakes up in an alley, bleeding and with ...",Comedy|Crime|Drama,1994-08-05,6.200,10.2127
655,1234731,Anaconda,A group of friends facing mid-life crises head...,Adventure|Comedy|Horror,2025-12-24,5.800,20.8848
2022,9360,Anaconda,A 'National Geographic' film crew is taken hos...,Adventure|Horror|Thriller,1997-04-11,5.284,11.5388

In [21]:
df_clean["overview"].str.len().describe()

count    8985.000000
mean      270.202894
std       146.298174
min         9.000000
25%       159.000000
50%       237.000000
75%       352.000000
max      1000.000000
Name: overview, dtype: float64

In [22]:
df_clean["overview"].str.strip().str.len().describe()

count    8985.000000
mean      270.202894
std       146.298174
min         9.000000
25%       159.000000
50%       237.000000
75%       352.000000
max      1000.000000
Name: overview, dtype: float64

In [23]:
df_clean["overview"].map(type).value_counts()

overview
<class 'str'>    8985
Name: count, dtype: int64

In [24]:
df_clean["genres"].map(type).value_counts()

genres
<class 'str'>    8985
Name: count, dtype: int64

In [25]:
df_clean.isnull().sum()

id               0
title            0
overview         0
genres           0
release_date    24
vote_average     0
popularity       0
dtype: int64

In [26]:
df_clean["id"].duplicated().sum()

np.int64(0)

In [27]:
df_clean.duplicated().sum()

np.int64(0)

In [28]:
df_clean.shape

(8985, 7)

In [30]:
df_clean.head(10)

,id,title,overview,genres,release_date,vote_average,popularity
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,Action|Adventure|Science Fiction,2026-07-29,7.865,839.8385
1,1204680,Coyote vs. Acme,After Acme products fail him one too many time...,Adventure|Comedy|Family,2026-08-20,7.685,654.7252
2,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",Action|Adventure|Fantasy,2026-07-15,7.998,464.1594
3,1288445,Mutiny,After witnessing his billionaire boss' murder ...,Action|Thriller,2026-08-19,6.382,408.1873
4,1375646,Colony,Professor Se-jeong is thrust into a bloody nig...,Action|Horror|Science Fiction,2026-05-21,8.098,318.9049
5,1386315,The Runner,"Maia Marten, a brilliant London lawyer, has he...",Action|Thriller,2026-09-03,6.700,312.0164
6,1285366,Shape of My Heart,"A romance about a man and a woman who, due to ...",Romance,2024-07-06,5.200,219.4042
7,1137844,Mayday,When a U.S. Navy pilot on a top-secret mission...,Action|Comedy,2026-09-03,7.965,237.3724
8,1393326,Ghost in the Cell,"In a notorious prison, an invisible force begi...",Comedy|Horror|Thriller,2026-04-16,7.128,217.3844
9,1506560,Clash of the Thundermans,When Chloe develops a destructive new superpow...,Action|Comedy|Family|Science Fiction|TV Movie,2026-09-03,6.909,214.9437

In [31]:
df_clean.to_csv("../data/processed/tmdb_movies_clean.csv", index=False)

In [32]:
import os

os.path.exists("../data/processed/tmdb_movies_clean.csv")

True

In [33]:
pd.read_csv("../data/processed/tmdb_movies_clean.csv").shape

(8985, 7)